services:

  app:
    container_name: "kentangapp"
    build: .
    # image: gofrendi/app-mock2
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080

  db:
    container_name: "kentangdb"
    image: bitnami/mysql
    # selalu restart container ini, kecuali container nya di stop
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=kentang
      - MYSQL_DATABASE=merdeka
    healthcheck:
      # perintah untuk memastikan bahwa mysql sudah ready
      test: ["CMD", "mysql", "-u", "root",  "-pkentang", "-e", "show schemas"]
      interval: 10s 

  adminer:
    container_name: "kentangadmin"
    image: adminer
    restart: unless-stopped
    ports: # host:container
      - 8081:8080
